export {Options,mixins} from 'vue-class-component'
export { State } from '@/decorators/state'
export { Action } from '@/decorators/action'
export { Getter } from '@/decorators/getter'
export { Mutation } from '@/decorators/mutation'
export { Watch } from '@/decorators/watch'
export { Provide } from '@/decorators/provide'
export { Inject } from '@/decorators/inject'